import { Html, Head, Main, NextScript } from 'next/document'

export default function Document() {
  return (
    <Html lang="en">
      <Head />
        {/* <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" /> */}
        <link href='https://www.fontspace.com/snes-font-f26537' ></link>
      <body>
        
        <Main />
        <NextScript />
      </body>
    </Html>
  )
}
